/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type AlertStatus = { 'resolved' : null } |
  { 'newAlert' : null } |
  { 'dispatched' : null } |
  { 'acknowledged' : null };
export type AlertType = { 'automatic' : null } |
  { 'manual' : null };
export interface ConditionNote {
  'name' : string,
  'type' : string,
  'description' : string,
}
export interface EmergencyAlert {
  'id' : bigint,
  'status' : AlertStatus,
  'patient' : Principal,
  'type' : AlertType,
  'timestamp' : bigint,
  'severity' : AlertSeverity,
}
export interface EmergencyContact {
  'relationship' : string,
  'name' : string,
  'phone' : string,
}
export interface HeartRateReading {
  'status' : ReadingStatus,
  'value' : bigint,
  'timestamp' : bigint,
}
export type ReadingStatus = { 'warning' : null } |
  { 'normal' : null } |
  { 'critical' : null };
export interface UserProfile {
  'age' : bigint,
  'knownConditionNoteId' : string,
  'name' : string,
  'emergencyContactsId' : string,
  'address' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addControlRoomUser' : ActorMethod<[Principal], undefined>,
  'addHeartRateReading' : ActorMethod<[HeartRateReading], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEmergencyAlert' : ActorMethod<[AlertType, AlertSeverity], bigint>,
  'getAlertDetails' : ActorMethod<[bigint], EmergencyAlert>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFullProfile' : ActorMethod<
    [Principal],
    [UserProfile, Array<EmergencyContact>, Array<ConditionNote>]
  >,
  'getHeartRateReadings' : ActorMethod<[Principal], Array<HeartRateReading>>,
  'getPendingAlerts' : ActorMethod<[], Array<EmergencyAlert>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isControlRoomUser' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserProfileWithContactNote' : ActorMethod<
    [UserProfile, Array<EmergencyContact>, Array<ConditionNote>],
    undefined
  >,
  'updateAlertStatus' : ActorMethod<[bigint, AlertStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];