/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReadingStatus = IDL.Variant({
  'warning' : IDL.Null,
  'normal' : IDL.Null,
  'critical' : IDL.Null,
});
export const HeartRateReading = IDL.Record({
  'status' : ReadingStatus,
  'value' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertType = IDL.Variant({
  'automatic' : IDL.Null,
  'manual' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const AlertStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'newAlert' : IDL.Null,
  'dispatched' : IDL.Null,
  'acknowledged' : IDL.Null,
});
export const EmergencyAlert = IDL.Record({
  'id' : IDL.Nat,
  'status' : AlertStatus,
  'patient' : IDL.Principal,
  'type' : AlertType,
  'timestamp' : IDL.Int,
  'severity' : AlertSeverity,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'knownConditionNoteId' : IDL.Text,
  'name' : IDL.Text,
  'emergencyContactsId' : IDL.Text,
  'address' : IDL.Text,
});
export const EmergencyContact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const ConditionNote = IDL.Record({
  'name' : IDL.Text,
  'type' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addControlRoomUser' : IDL.Func([IDL.Principal], [], []),
  'addHeartRateReading' : IDL.Func([HeartRateReading], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEmergencyAlert' : IDL.Func([AlertType, AlertSeverity], [IDL.Nat], []),
  'getAlertDetails' : IDL.Func([IDL.Nat], [EmergencyAlert], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFullProfile' : IDL.Func(
      [IDL.Principal],
      [UserProfile, IDL.Vec(EmergencyContact), IDL.Vec(ConditionNote)],
      ['query'],
    ),
  'getHeartRateReadings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(HeartRateReading)],
      ['query'],
    ),
  'getPendingAlerts' : IDL.Func([], [IDL.Vec(EmergencyAlert)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isControlRoomUser' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserProfileWithContactNote' : IDL.Func(
      [UserProfile, IDL.Vec(EmergencyContact), IDL.Vec(ConditionNote)],
      [],
      [],
    ),
  'updateAlertStatus' : IDL.Func([IDL.Nat, AlertStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReadingStatus = IDL.Variant({
    'warning' : IDL.Null,
    'normal' : IDL.Null,
    'critical' : IDL.Null,
  });
  const HeartRateReading = IDL.Record({
    'status' : ReadingStatus,
    'value' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertType = IDL.Variant({
    'automatic' : IDL.Null,
    'manual' : IDL.Null,
  });
  const AlertSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AlertStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'newAlert' : IDL.Null,
    'dispatched' : IDL.Null,
    'acknowledged' : IDL.Null,
  });
  const EmergencyAlert = IDL.Record({
    'id' : IDL.Nat,
    'status' : AlertStatus,
    'patient' : IDL.Principal,
    'type' : AlertType,
    'timestamp' : IDL.Int,
    'severity' : AlertSeverity,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'knownConditionNoteId' : IDL.Text,
    'name' : IDL.Text,
    'emergencyContactsId' : IDL.Text,
    'address' : IDL.Text,
  });
  const EmergencyContact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ConditionNote = IDL.Record({
    'name' : IDL.Text,
    'type' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addControlRoomUser' : IDL.Func([IDL.Principal], [], []),
    'addHeartRateReading' : IDL.Func([HeartRateReading], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEmergencyAlert' : IDL.Func(
        [AlertType, AlertSeverity],
        [IDL.Nat],
        [],
      ),
    'getAlertDetails' : IDL.Func([IDL.Nat], [EmergencyAlert], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFullProfile' : IDL.Func(
        [IDL.Principal],
        [UserProfile, IDL.Vec(EmergencyContact), IDL.Vec(ConditionNote)],
        ['query'],
      ),
    'getHeartRateReadings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(HeartRateReading)],
        ['query'],
      ),
    'getPendingAlerts' : IDL.Func([], [IDL.Vec(EmergencyAlert)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isControlRoomUser' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserProfileWithContactNote' : IDL.Func(
        [UserProfile, IDL.Vec(EmergencyContact), IDL.Vec(ConditionNote)],
        [],
        [],
      ),
    'updateAlertStatus' : IDL.Func([IDL.Nat, AlertStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };