/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HeartRateReading {
    status: ReadingStatus;
    value: bigint;
    timestamp: bigint;
}
export interface EmergencyAlert {
    id: bigint;
    status: AlertStatus;
    patient: Principal;
    type: AlertType;
    timestamp: bigint;
    severity: AlertSeverity;
}
export interface EmergencyContact {
    relationship: string;
    name: string;
    phone: string;
}
export interface ConditionNote {
    name: string;
    type: string;
    description: string;
}
export interface UserProfile {
    age: bigint;
    knownConditionNoteId: string;
    name: string;
    emergencyContactsId: string;
    address: string;
}
export enum AlertSeverity {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum AlertStatus {
    resolved = "resolved",
    newAlert = "newAlert",
    dispatched = "dispatched",
    acknowledged = "acknowledged"
}
export enum AlertType {
    automatic = "automatic",
    manual = "manual"
}
export enum ReadingStatus {
    warning = "warning",
    normal = "normal",
    critical = "critical"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addControlRoomUser(user: Principal): Promise<void>;
    addHeartRateReading(reading: HeartRateReading): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEmergencyAlert(type: AlertType, severity: AlertSeverity): Promise<bigint>;
    getAlertDetails(alertId: bigint): Promise<EmergencyAlert>;
    getAllAlerts(): Promise<Array<EmergencyAlert>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFullProfile(user: Principal): Promise<[UserProfile, Array<EmergencyContact>, Array<ConditionNote>]>;
    getHeartRateReadings(user: Principal): Promise<Array<HeartRateReading>>;
    getMyAlerts(): Promise<Array<EmergencyAlert>>;
    getPendingAlerts(): Promise<Array<EmergencyAlert>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isControlRoomUser(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveUserProfileWithContactNote(profile: UserProfile, contacts: Array<EmergencyContact>, notes: Array<ConditionNote>): Promise<void>;
    updateAlertStatus(alertId: bigint, status: AlertStatus): Promise<void>;
}
import type { AlertSeverity as _AlertSeverity, AlertStatus as _AlertStatus, AlertType as _AlertType, EmergencyAlert as _EmergencyAlert, HeartRateReading as _HeartRateReading, ReadingStatus as _ReadingStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addControlRoomUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addControlRoomUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addControlRoomUser(arg0);
            return result;
        }
    }
    async addHeartRateReading(arg0: HeartRateReading): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHeartRateReading(to_candid_HeartRateReading_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHeartRateReading(to_candid_HeartRateReading_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEmergencyAlert(arg0: AlertType, arg1: AlertSeverity): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmergencyAlert(to_candid_AlertType_n7(this._uploadFile, this._downloadFile, arg0), to_candid_AlertSeverity_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmergencyAlert(to_candid_AlertType_n7(this._uploadFile, this._downloadFile, arg0), to_candid_AlertSeverity_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAlertDetails(arg0: bigint): Promise<EmergencyAlert> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertDetails(arg0);
                return from_candid_EmergencyAlert_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertDetails(arg0);
            return from_candid_EmergencyAlert_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAlerts(): Promise<Array<EmergencyAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlerts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlerts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFullProfile(arg0: Principal): Promise<[UserProfile, Array<EmergencyContact>, Array<ConditionNote>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullProfile(arg0);
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullProfile(arg0);
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getHeartRateReadings(arg0: Principal): Promise<Array<HeartRateReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeartRateReadings(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeartRateReadings(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAlerts(): Promise<Array<EmergencyAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAlerts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAlerts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingAlerts(): Promise<Array<EmergencyAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingAlerts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingAlerts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isControlRoomUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isControlRoomUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isControlRoomUser();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveUserProfileWithContactNote(arg0: UserProfile, arg1: Array<EmergencyContact>, arg2: Array<ConditionNote>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfileWithContactNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfileWithContactNote(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAlertStatus(arg0: bigint, arg1: AlertStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlertStatus(arg0, to_candid_AlertStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlertStatus(arg0, to_candid_AlertStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AlertSeverity_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_AlertStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertStatus): AlertStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AlertType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_EmergencyAlert_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmergencyAlert): EmergencyAlert {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_HeartRateReading_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeartRateReading): HeartRateReading {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ReadingStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReadingStatus): ReadingStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AlertStatus;
    patient: Principal;
    type: _AlertType;
    timestamp: bigint;
    severity: _AlertSeverity;
}): {
    id: bigint;
    status: AlertStatus;
    patient: Principal;
    type: AlertType;
    timestamp: bigint;
    severity: AlertSeverity;
} {
    return {
        id: value.id,
        status: from_candid_AlertStatus_n13(_uploadFile, _downloadFile, value.status),
        patient: value.patient,
        type: from_candid_AlertType_n15(_uploadFile, _downloadFile, value.type),
        timestamp: value.timestamp,
        severity: from_candid_AlertSeverity_n17(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReadingStatus;
    value: bigint;
    timestamp: bigint;
}): {
    status: ReadingStatus;
    value: bigint;
    timestamp: bigint;
} {
    return {
        status: from_candid_ReadingStatus_n26(_uploadFile, _downloadFile, value.status),
        value: value.value,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    newAlert: null;
} | {
    dispatched: null;
} | {
    acknowledged: null;
}): AlertStatus {
    return "resolved" in value ? AlertStatus.resolved : "newAlert" in value ? AlertStatus.newAlert : "dispatched" in value ? AlertStatus.dispatched : "acknowledged" in value ? AlertStatus.acknowledged : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    automatic: null;
} | {
    manual: null;
}): AlertType {
    return "automatic" in value ? AlertType.automatic : "manual" in value ? AlertType.manual : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): AlertSeverity {
    return "low" in value ? AlertSeverity.low : "high" in value ? AlertSeverity.high : "medium" in value ? AlertSeverity.medium : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    normal: null;
} | {
    critical: null;
}): ReadingStatus {
    return "warning" in value ? ReadingStatus.warning : "normal" in value ? ReadingStatus.normal : "critical" in value ? ReadingStatus.critical : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmergencyAlert>): Array<EmergencyAlert> {
    return value.map((x)=>from_candid_EmergencyAlert_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HeartRateReading>): Array<HeartRateReading> {
    return value.map((x)=>from_candid_HeartRateReading_n24(_uploadFile, _downloadFile, x));
}
function to_candid_AlertSeverity_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): _AlertSeverity {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_AlertStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertStatus): _AlertStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_AlertType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): _AlertType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_HeartRateReading_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeartRateReading): _HeartRateReading {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ReadingStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReadingStatus): _ReadingStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ReadingStatus;
    value: bigint;
    timestamp: bigint;
}): {
    status: _ReadingStatus;
    value: bigint;
    timestamp: bigint;
} {
    return {
        status: to_candid_ReadingStatus_n3(_uploadFile, _downloadFile, value.status),
        value: value.value,
        timestamp: value.timestamp
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == AlertSeverity.low ? {
        low: null
    } : value == AlertSeverity.high ? {
        high: null
    } : value == AlertSeverity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertStatus): {
    resolved: null;
} | {
    newAlert: null;
} | {
    dispatched: null;
} | {
    acknowledged: null;
} {
    return value == AlertStatus.resolved ? {
        resolved: null
    } : value == AlertStatus.newAlert ? {
        newAlert: null
    } : value == AlertStatus.dispatched ? {
        dispatched: null
    } : value == AlertStatus.acknowledged ? {
        acknowledged: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReadingStatus): {
    warning: null;
} | {
    normal: null;
} | {
    critical: null;
} {
    return value == ReadingStatus.warning ? {
        warning: null
    } : value == ReadingStatus.normal ? {
        normal: null
    } : value == ReadingStatus.critical ? {
        critical: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): {
    automatic: null;
} | {
    manual: null;
} {
    return value == AlertType.automatic ? {
        automatic: null
    } : value == AlertType.manual ? {
        manual: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
